version: "3.0"
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: web
    user: root
    restart: always
    ports:
      - 8080:8080
    environment:
      - "WEB_SCHEME=http"
      - "WEB_HOST=0.0.0.0"
      - "WEB_PORT=8080"
      - "WEB_BASE=/api/v1"
      - "DB_HOST=db"
      - "DB_PORT=27017"
      - "HTTP_SERVER_ADDRESS=http://0.0.0.0.8080"
      - "LOG_LEVEL=DEBUG"
    depends_on:
      - db
    networks:
      - db

  db:
    image: mongo
    restart: always
    user: root
    volumes:
      - ./db:/data/db:rw
    ports:
      - 127.0.0.1:37020:27017
    networks:
     - db

networks:
  db:
    driver: bridge