# coding: utf-8

# flake8: noqa

"""
    Python Users API

    This is a simple Users API. It provides basic logic, CRUD operations of users.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: valentin.sheboldaev@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.user_api import UserApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.error import Error
from swagger_client.models.get_total_users import GetTotalUsers
from swagger_client.models.link_description import LinkDescription
from swagger_client.models.links import Links
from swagger_client.models.user import User
from swagger_client.models.users import Users
