# coding: utf-8

"""
    Python Users API

    This is a simple Users API. It provides basic logic, CRUD operations of users.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: valentin.sheboldaev@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_api_api import UserAPIApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserAPIApi(unittest.TestCase):
    """UserAPIApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.user_api_api.UserAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_useruser_uuid_post(self):
        """Test case for delete_useruser_uuid_post

        Delete a single user record  # noqa: E501
        """
        pass

    def test_get_total_users_get(self):
        """Test case for get_total_users_get

        Get all system users  # noqa: E501
        """
        pass

    def test_get_user_by_emailuser_email_get(self):
        """Test case for get_user_by_emailuser_email_get

        Get's a single user record  # noqa: E501
        """
        pass

    def test_get_user_by_uuiduser_uuid_get(self):
        """Test case for get_user_by_uuiduser_uuid_get

        Get's a single user record  # noqa: E501
        """
        pass

    def test_post_user_post(self):
        """Test case for post_user_post

        Adds a single user record  # noqa: E501
        """
        pass

    def test_post_users_post(self):
        """Test case for post_users_post

        Adds users to User db. Upload as many as you want.  # noqa: E501
        """
        pass

    def test_update_useruser_uuid_put(self):
        """Test case for update_useruser_uuid_put

        Updates an existing user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
