# coding: utf-8

"""
    Python Users API

    This is a simple Users API. It provides basic logic, CRUD operations of users.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: valentin.sheboldaev@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class LinkDescription(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'href': 'str',
        'rel': 'str',
        'title': 'str',
        'media_type': 'str',
        'method': 'str',
        'enc_type': 'str'
    }

    attribute_map = {
        'href': 'href',
        'rel': 'rel',
        'title': 'title',
        'media_type': 'mediaType',
        'method': 'method',
        'enc_type': 'encType'
    }

    def __init__(self, href=None, rel=None, title=None, media_type='application/json', method='(Optional) GET', enc_type='application/json'):  # noqa: E501
        """LinkDescription - a model defined in Swagger"""  # noqa: E501

        self._href = None
        self._rel = None
        self._title = None
        self._media_type = None
        self._method = None
        self._enc_type = None
        self.discriminator = None

        self.href = href
        self.rel = rel
        if title is not None:
            self.title = title
        if media_type is not None:
            self.media_type = media_type
        if method is not None:
            self.method = method
        if enc_type is not None:
            self.enc_type = enc_type

    @property
    def href(self):
        """Gets the href of this LinkDescription.  # noqa: E501

        a URI template, as defined by RFC 6570, with the addition of the $, ( and ) characters for pre-processing  # noqa: E501

        :return: The href of this LinkDescription.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this LinkDescription.

        a URI template, as defined by RFC 6570, with the addition of the $, ( and ) characters for pre-processing  # noqa: E501

        :param href: The href of this LinkDescription.  # noqa: E501
        :type: str
        """
        if href is None:
            raise ValueError("Invalid value for `href`, must not be `None`")  # noqa: E501

        self._href = href

    @property
    def rel(self):
        """Gets the rel of this LinkDescription.  # noqa: E501

        relation to the target user of the link  # noqa: E501

        :return: The rel of this LinkDescription.  # noqa: E501
        :rtype: str
        """
        return self._rel

    @rel.setter
    def rel(self, rel):
        """Sets the rel of this LinkDescription.

        relation to the target user of the link  # noqa: E501

        :param rel: The rel of this LinkDescription.  # noqa: E501
        :type: str
        """
        if rel is None:
            raise ValueError("Invalid value for `rel`, must not be `None`")  # noqa: E501

        self._rel = rel

    @property
    def title(self):
        """Gets the title of this LinkDescription.  # noqa: E501

        a title for the link  # noqa: E501

        :return: The title of this LinkDescription.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this LinkDescription.

        a title for the link  # noqa: E501

        :param title: The title of this LinkDescription.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def media_type(self):
        """Gets the media_type of this LinkDescription.  # noqa: E501

        media type (as defined by RFC 2046) describing the link target  # noqa: E501

        :return: The media_type of this LinkDescription.  # noqa: E501
        :rtype: str
        """
        return self._media_type

    @media_type.setter
    def media_type(self, media_type):
        """Sets the media_type of this LinkDescription.

        media type (as defined by RFC 2046) describing the link target  # noqa: E501

        :param media_type: The media_type of this LinkDescription.  # noqa: E501
        :type: str
        """

        self._media_type = media_type

    @property
    def method(self):
        """Gets the method of this LinkDescription.  # noqa: E501

        method for requesting the target of the link (e.g. for HTTP this might be 'GET' or 'DELETE')  # noqa: E501

        :return: The method of this LinkDescription.  # noqa: E501
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method):
        """Sets the method of this LinkDescription.

        method for requesting the target of the link (e.g. for HTTP this might be 'GET' or 'DELETE')  # noqa: E501

        :param method: The method of this LinkDescription.  # noqa: E501
        :type: str
        """

        self._method = method

    @property
    def enc_type(self):
        """Gets the enc_type of this LinkDescription.  # noqa: E501

        The media type in which to submit data along with the request  # noqa: E501

        :return: The enc_type of this LinkDescription.  # noqa: E501
        :rtype: str
        """
        return self._enc_type

    @enc_type.setter
    def enc_type(self, enc_type):
        """Sets the enc_type of this LinkDescription.

        The media type in which to submit data along with the request  # noqa: E501

        :param enc_type: The enc_type of this LinkDescription.  # noqa: E501
        :type: str
        """

        self._enc_type = enc_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LinkDescription, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LinkDescription):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
